version: "3.10"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    environment:
      CONFIG: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql://username:passwd!@pg:5432/school
    ports:
      - "8000:80"
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d school -U username" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db-data: